### ISSUE TITLE
AA adds stars in the darkness.

### ISSUE THREAD

**Issue by JamesBong0070** [Jasson9/ContentWarning-MoreSettings#1]
I was able to resolve this by overriding the AA with supersampling via AMD Adrenaline.

**Comment by Jasson9** [comment]
This was actually a bug from earlier Unity version from this post: [Jaggy white pixel artifacts on edges with specular and antialiasing](https://forum.unity.com/threads/jaggy-white-pixel-artifacts-on-edges-with-specular-and-antialiasing.320984/)

The anti-aliasing of specular material can produce white artifacts at the edges. In this case the old-world trees are specular material. Added with bloom effect from the post processing, those white artifacts will look like a shining star. The current implementation is using MSAA 8x + SMAA which produce great AA quality but create a lot of white artifacts. 

After my testing using only SMAA will produce small number of white artifacts, using TAA will resulting in flickering HUD text, FXAA have similar result with SMAA but with lower AA quality but better performance.

For now I'm going to implement FXAA and SMAA for the AA. Also, thanks for your the feedback.

**Comment by JamesBong0070** [comment]
Ah I see, at least I can use your mod to use FSR/Render Scale with supersampling so I don't lose frames and have a better image XD.
